version: 0.2
phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region ap-northeast-1)
      - REPO=643526083873.dkr.ecr.ap-northeast-1.amazonaws.com/pipeline-application/pipeline-frontend
      - IMAGE=$REPO:latest
  build:
    commands:
      - docker build -t $IMAGE .
      - docker push $IMAGE
  post_build:
    commands:
      - printf '[{"name":"pipeline-frontend","imageUri":"%s"}]' $IMAGE > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
